---
version: '3.4'

x-app: &x-app
  build: .
  volumes:
    - .:/app:delegated

services:
  app:
    <<: *x-app
    command: yarn run nuxt --port 3000 --hostname 0.0.0.0
    ports:
      - "127.0.0.1:3000:3000"
